### ISSUE TITLE
Don't escape HTML in plain text emails

### ISSUE THREAD

**Issue by kenn** [brianmario/escape_utils#15]
I've found a similar ticket reported here, but it was closed without a fix so I'm re-raising the issue. (Rails 3.0.7 + Ruby 1.9.2)

https://github.com/brianmario/escape_utils/issues/14

In my case, not only `'/'` was escaped but other characters like single quotes got escaped too. So `EscapeUtils.html_secure = false` only fixed the url part of the problem.

Namely, with `require 'escape_utils/html/erb'`:

```
Here&#39;s the link: http:&#47;&#47;www.example.com&#47;
```

With `require 'escape_utils/html/erb'` and `EscapeUtils.html_secure = false`:

```
Here&#39;s the link: http://www.example.com/
```

By removing `require 'escape_utils/html/erb'`, finally I got the correct result:

```
Here's the link: http://www.example.com/
```

Note that HTML tags like `'<'` or `'>'` aren't escaped in email templates with `.text.erb` extension, so it's not a Rails bug.

**Comment by byroot** [comment]
HTML escaping capabilities are deprecated in 1.3 because Ruby's `CGI.escapeHTML` is now faster.
