### ISSUE TITLE
Option to not use "+" in escape_url

### ISSUE THREAD

**Issue by hannesg** [brianmario/escape_utils#21]
Hi
following problem:
I'm implementing [this uri-template spec](http://tools.ietf.org/html/draft-gregorio-uritemplate-07). I could realy use a version of escape_url without the "+"  for whitespace, since this behavior is defined in the spec. Rereplacing the pluses afterward with "%20" is not a good option as this more than doubles the runtime, which is too expensive imho.

If i write a method escape_url2 with this behavior, would you pull it?

**Comment by casperisfine** [comment]
We already have this:

```ruby
>> EscapeUtils.escape_url(" ")
=> "+"
>> EscapeUtils.escape_uri(" ")
=> "%20"
```
