### ISSUE TITLE
escape_javascript monkeypatch breaks existing ajax js response behavior

### ISSUE THREAD

**Issue by joe1chen** [brianmario/escape_utils#43]
We're using Rails 3.2.12.  In our application we have ajax pagination of a view.

index.js.haml

``` ruby
$('#activity_stream').html("#{escape_javascript render("activities/activity_stream", :stream => @activity_stream)}");
```

The default ajax response when not using escape_utils is something like this:

``` javascript
$('#activity_stream').html("<ul class=\'streams\'>\n  <li id=\'s ...
```

When using escape_utils javascript action_view monkeypatch, the ajax response looks something like this:

``` javascript
$('#activity_stream').html("&lt;ul class=\&#39;streams\&#39;&gt;\n  &lt;li id=\&#39;s ...
```

Instead of rendering HTML, now it's rendering an HTML-escaped string. The monkeypatch doesn't seem to be working.  Shouldn't it be a drop-in replacement for the original escape_javascript?

**Comment by westonganger** [comment]
This gem is not compatible with Rails 4.2 as well

**Comment by CHTJonas** [comment]
Still an issue with Rails 5.2.2
