### ISSUE TITLE
escape_utils/url/uri breaks oauth

### ISSUE THREAD

**Issue by hrdwdmrbl** [brianmario/escape_utils#58]
The OAuth library uses CGI::escape to encode request headers. CGI::escape will escape = (equal sign), but EscapeUtils.escape_uri does not. As a result, OAuth produces mal-formed headers.

**Comment by byroot** [comment]
```
>> EscapeUtils::VERSION
=> "1.2.1"
>> EscapeUtils.escape_url('=')
=> "%3D"
```

Not sure when it was fixed, but we can close this.
