### ISSUE TITLE
escape_util is not working properly

### ISSUE THREAD

**Issue by junaid-malik-confiz** [brianmario/escape_utils#67]
Hello,

I tried gem escape_utils but it is not working as intended. I have also done following configuration changes in intializers.

 require 'escape_utils/html/rack' # to patch Rack::Utils
   require 'escape_utils/html/erb' # to patch ERB::Util
   require 'escape_utils/html/cgi' # to patch CGI
   require 'escape_utils/html/haml' # to patch Haml::Helpers
   require 'escape_utils/url/cgi' # to patch CGI
   require 'escape_utils/url/erb' # to patch ERB::Util
   require 'escape_utils/url/rack' # to patch Rack::Utils
   require 'escape_utils/url/uri' # to patch URI
   require 'escape_utils/javascript/action_view' # to patch ActionView::Helpers::JavaScriptHelper

It is not escaping asset_path or links in html.e.g 

<meta property="al:ios:url" content="pakwheels:/&#47;"/>
<link rel="alternate" href="ios-app:&#47;&#47;739776365&#47;pakwheels&#47;"/>
loadCSS("&#47;assets&#47;fonts-base64-woff.css");

Below is the code that is generating above html.
<meta property="al:ios:url" content="<%=FB_DEEP_LINK_SCHEME%>:/<%=request.path%>"/>
<meta property="al:ios:app_store_id" content="<%=IOS_APP_STORE_ID%>" />
<meta property="al:ios:app_name" content="<%=IOS_APP_NAME%>" />
<link rel="alternate" href="<%="#{IOS_DEEP_LINK}#{request.path}"%>"/>
loadCSS("<%= asset_path 'pwbodyicons.css' %>");

Anyone can help to resolve this. I am using Rails 3.2.19 and Ruby ruby 2.1.2p95. One solution is to unescape ourself which can't be done on many places. 

Regards,
Junaid

**Comment by byroot** [comment]
Closing as non actionable. `escape_utils` drifted quite a lot with the methods it replaced, I'm fixing them the best I can, but this issue isn't helpful.
